<a href="https://colab.research.google.com/github/nazuna-0/WorkSheets_AshwiniTamang/blob/main/WorkSheet_1_AshwiniTamang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 4.1
import numpy as np

#Initialize an empty array with size 2X2.
arr1 = np.empty((2,2))

#Initialize an all ones array with size 4X2.
arr2 = np.ones((4, 2))

#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr_full = np.full((3, 3), 7)

#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
given = np.array([[5,6,7],[8,9,10]])
arr_zeros_like = np.zeros_like(given)
arr_zeros_like

#Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
arr_ones_like = np.ones_like(given)
arr_ones_like

#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]

np_array = np.array(new_list)
np_array

# Task 1

arr1 = np.arange(10,50)
arr1

# Task 2

mat3 = np.arange(9).reshape(3,3)
mat3

identity = np.eye(5)
identity

# Task 3

rand_arr = np.random.random(30)
mean_val = rand_arr.mean()

rand_arr, mean_val

# Task 4

rand10 = np.random.random((10,10))
rand_min = rand10.min()
rand_max = rand10.max()

rand_min, rand_max

# Task 5

zero_arr = np.zeros(10)
zero_arr[4] = 1
zero_arr

# Task 6

arr7 = np.array([1,2,0,0,4,0])
reversed_arr = arr7[::-1]
reversed_arr

# Task 7

border_arr = np.ones((5,5))
border_arr[1:-1, 1:-1] = 0
border_arr

# Task 8

checkboard = np.zeros((8,8))
checkboard[1::2, ::2] = 1
checkboard[::2, 1::2] = 1
checkboard



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# Task 3

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# add the two arrays
add_xy = x + y
add_xy

# substract the two arrays
sub_xy = x - y
sub_xy

#Multiply the array with any int
mul_x = x * 3
mul_x

#Square each element of the array
square_x = x ** 2
square_x

#Dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v,w)
dot_vw

#Concatenate x(and)y along row and Concatenate v(and)w along column.
dot_xv = np.dot(x,v)
dot_xv

#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
concat_row_xy = np.concatenate((x, y), axis=0)
concat_row_xy


array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [ ]:
# Task 4

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

# Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
I

# Prove AB ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)

AB, BA

# Prove (AB)T = (B)T(A)T

AB = np.dot(A, B)
left_side = AB.T

right_side = np.dot(B.T, A.T)

left_side, right_side

#
A= np.array([[2, -3, 1],
             [1, -1, 2],
             [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
solution = np.dot(A_inv, B)

solution

array([ 2.,  1., -2.])

In [3]:
# EXPERIMENTIN NUMPY VS SLOW PYTHON

import time
import numpy as np

size = 1_000_000
matrix_size = 1000

# Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

# Addition
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Addition Time:", end - start)

# Multiplication
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Multiplication Time:", end - start)

# Dot Product
start = time.time()
dot = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start)

# Matrix Multiplication
mat1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
mat2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
start = time.time()
mat_result = mat1 @ mat2
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)


NumPy Addition Time: 0.006220102310180664
NumPy Multiplication Time: 0.007228374481201172
NumPy Dot Product Time: 0.00241851806640625
NumPy Matrix Multiplication Time: 2.4777989387512207
